Updates test.py to use Python's unittest, to run the `pytype` static analyzer, and to connect to a configurable target device for the integration test.
The integration test needs to be updated to match the current pychromecast API.

Sample output:
```
$./test.py
testPytype (__main__.MkchromecastTests.testPytype) ... FAIL
testZZEndToEndIntegration (__main__.MkchromecastTests.testZZEndToEndIntegration) ... skipped 'Specify --test-connect-to to run integration test'

======================================================================
FAIL: testPytype (__main__.MkchromecastTests.testPytype)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/xsdg/files/compile/mkcc/mkchromecast/./test.py", line 50, in testPytype
    self.fail(pytype_result.stdout)
AssertionError: ninja: Entering directory `../../../../../../tmp/tmpv_tfw_45'
[1/24] check mkchromecast.version
[2/24] check mkchromecast.resolution
[3/24] check mkchromecast.colors
FAILED: /tmp/tmpv_tfw_45/pyi/mkchromecast/colors.pyi
/home/xsdg/.local/pipx/venvs/pytype/bin/python -m pytype.single --imports_info /tmp/tmpv_tfw_45/imports/mkchromecast.colors.imports --module-name mkchromecast.colors --platform linux -V 3.11 -o /tmp/tmpv_tfw_45/pyi/mkchromecast/colors.pyi --analyze-annotated --nofail --quick --use-enum-overlay /home/xsdg/files/compile/mkcc/mkchromecast/mkchromecast/colors.py
File "/home/xsdg/files/compile/mkcc/mkchromecast/mkchromecast/colors.py", line 5, in <module>: Name 'unicode' is not defined [name-error]

For more details, see https://google.github.io/pytype/errors.html#name-error
[...]
----------------------------------------------------------------------
Ran 2 tests in 6.235s

FAILED (failures=1, skipped=1)
```