FileNotFoundError: [Errno 2] No such file or directory: 'lame': 'lame'
This commit introduces a try/except to check if lame is not installed.
It closes #258. Thanks to @axj336.