mkchromecast/tray_threading.py", line 84, in _play_cast_ causing AttributeError: 'casting' object has no attribute 'castto' is being treated in this commit.